<?php

return [
    'accepted' => ':attribute kabul edilmelidir.',
    'active_url' => ':attribute gecerli bir URL degil.',
    'after' => ':attribute, :date tarihinden sonra olmalidir.',
    'after_or_equal' => ':attribute, :date tarihinden sonra veya ayni tarih olmalidir.',
    'alpha' => ':attribute yalnizca harf icerebilir.',
    'alpha_dash' => ':attribute yalnizca harf, rakam ve tire icerebilir.',
    'alpha_num' => ':attribute yalnizca harf ve rakam icerebilir.',
    'array' => ':attribute bir dizi olmalidir.',
    'before' => ':attribute, :date tarihinden once olmalidir.',
    'before_or_equal' => ':attribute, :date tarihinden once veya ayni tarih olmalidir.',
    'between' => [
        'numeric' => ':attribute, :min ile :max arasinda olmalidir.',
        'file' => ':attribute, :min ile :max kilobayt arasinda olmalidir.',
        'string' => ':attribute, :min ile :max karakter arasinda olmalidir.',
        'array' => ':attribute, :min ile :max oge arasinda olmalidir.',
    ],
    'boolean' => ':attribute alani dogru veya yanlis olmalidir.',
    'confirmed' => ':attribute onayi eslesmiyor.',
    'date' => ':attribute gecerli bir tarih degil.',
    'date_format' => ':attribute, :format formatina uymalidir.',
    'different' => ':attribute ve :other farkli olmalidir.',
    'digits' => ':attribute, :digits basamakli olmalidir.',
    'digits_between' => ':attribute, :min ile :max arasinda basamakli olmalidir.',
    'dimensions' => ':attribute gecersiz resim boyutlarina sahip.',
    'distinct' => ':attribute alani tekrarlayan bir degere sahiptir.',
    'email' => ':attribute gecerli bir e-posta adresi olmalidir.',
    'exists' => 'Secilen :attribute gecersiz.',
    'file' => ':attribute bir dosya olmalidir.',
    'filled' => ':attribute alani doldurulmalidir.',
    'image' => ':attribute bir resim olmalidir.',
    'in' => 'Secilen :attribute gecersiz.',
    'in_array' => ':attribute alani :other icinde mevcut degil.',
    'integer' => ':attribute bir tam sayi olmalidir.',
    'ip' => ':attribute gecerli bir IP adresi olmalidir.',
    'json' => ':attribute gecerli bir JSON dizgesi olmalidir.',
    'max' => [
        'numeric' => ':attribute, :max degerinden buyuk olmamalidir.',
        'file' => ':attribute, :max kilobayttan buyuk olmamalidir.',
        'string' => ':attribute, :max karakterden buyuk olmamalidir.',
        'array' => ':attribute, :max ogeden fazla olmamalidir.',
    ],
    'mimes' => ':attribute, :values turunde bir dosya olmalidir.',
    'mimetypes' => ':attribute, :values turunde bir dosya olmalidir.',
    'min' => [
        'numeric' => ':attribute en az :min olmalidir.',
        'file' => ':attribute en az :min kilobayt olmalidir.',
        'string' => ':attribute en az :min karakter olmalidir.',
        'array' => ':attribute en az :min oge icermelidir.',
    ],
    'not_in' => 'Secilen :attribute gecersiz.',
    'numeric' => ':attribute bir sayi olmalidir.',
    'present' => ':attribute alani mevcut olmalidir.',
    'regex' => ':attribute formati gecersiz.',
    'required' => ':attribute alani gereklidir.',
    'required_if' => ':attribute alani, :other :value ise gereklidir.',
    'required_unless' => ':attribute alani, :other :values icinde olmadikca gereklidir.',
    'required_with' => ':values mevcut oldugunda :attribute alani gereklidir.',
    'required_with_all' => ':values mevcut oldugunda :attribute alani gereklidir.',
    'required_without' => ':values mevcut olmadiginda :attribute alani gereklidir.',
    'required_without_all' => ':values hicbiri mevcut olmadiginda :attribute alani gereklidir.',
    'same' => ':attribute ve :other eslesmelidir.',
    'size' => [
        'numeric' => ':attribute, :size olmalidir.',
        'file' => ':attribute, :size kilobayt olmalidir.',
        'string' => ':attribute, :size karakter olmalidir.',
        'array' => ':attribute, :size oge icermelidir.',
    ],
    'string' => ':attribute bir metin olmalidir.',
    'timezone' => ':attribute gecerli bir saat dilimi olmalidir.',
    'unique' => ':attribute zaten alinmis.',
    'uploaded' => ':attribute yuklenemedi.',
    'url' => ':attribute formati gecersiz.',
    'attributes' => [],
    'internal' => [
        'variable_value' => ':env degiskeni',
        'invalid_password' => 'Saglanan sifre bu hesap icin gecersiz.',
    ],
];
